# ruff: noqa: F401
from __future__ import annotations

from .plotting_basic import (
    origin_plot_3d_scatter,
    origin_plot_3d_surface,
    origin_plot_box,
    origin_plot_column,
    origin_plot_contour,
    origin_plot_dual_y,
    origin_plot_errorbar,
    origin_plot_heatmap,
    origin_plot_histogram,
    origin_plot_line,
    origin_plot_line_symbol,
    origin_plot_polar,
    origin_plot_scatter,
    origin_plot_table_id,
)
from .plotting_plot_ids import (
    _plot_matrix_route,
    _pti,
    origin_plot,
    origin_plot_3d_bars,
    origin_plot_3d_errorbar,
    origin_plot_3d_ribbon,
    origin_plot_3d_vector,
    origin_plot_area,
    origin_plot_bar,
    origin_plot_bubble,
    origin_plot_bubble_color_mapped,
    origin_plot_candlestick,
    origin_plot_color_mapped,
    origin_plot_column_stack,
    origin_plot_dendrogram,
    origin_plot_fill_area,
    origin_plot_floating_bar,
    origin_plot_high_low_close,
    origin_plot_image,
    origin_plot_matrix_3d_scatter,
    origin_plot_matrix_3d_surface,
    origin_plot_matrix_contour,
    origin_plot_matrix_heatmap,
    origin_plot_matrix_id,
    origin_plot_pie,
    origin_plot_polar_xr_ytheta,
    origin_plot_smith,
    origin_plot_stack_area,
    origin_plot_stack_bar,
    origin_plot_ternary,
    origin_plot_ternary_contour,
    origin_plot_vector_xyam,
    origin_plot_vector_xyxy,
    origin_plot_waterfall,
)
from .plotting_routing import (
    origin_batch_plot_from_template,
    origin_chart_atlas_route,
    origin_plot_auto,
    origin_plot_chart_atlas,
    origin_plot_from_range,
    origin_recommend_chart,
)
from .plotting_shared import (
    MATRIX_PLOT_TYPE_ID_ROUTES,
    PLOT_TYPE_ID_ROUTES,
    _plot_csv,
    _plot_table_id,
)
